### ISSUE TITLE
Issue with "git rdm ls"

### ISSUE THREAD

**Issue by larsvilhuber** [ctjacobs/git-rdm#3]
I ran into an issue where "git rdm ls" would not show files. 

Context: 
`Linux  3.16.7-29-desktop, OpenSUSE 13.2, Anaconda Python, conda 4.3.15, Python 2.7.13 :: Anaconda 4.3.1 (64-bit)
`
installation of git-rdm:
`Package plan for installation in environment /opt/anaconda3/envs/git-rdm:

The following NEW packages will be INSTALLED:

    git-rdm:     1.0.1-py27_0               ctjacobs
    gitdb:       0.6.4-py27_0               ioos
    gitpython:   2.0.8-py27_0               ioos
    http-parser: 0.8.3-py27_0               auto
    httplib2:    0.8-py27_0                 auto
    pyrdm:       0.3-py27_0                 ctjacobs
    restkit:     4.2.2-py27_0               auto
    smmap:       0.9.0-py27_0               ioos
    socketpool:  0.5.3-py27_0               auto
    sword2:      0.1.15.cc7c6a42843d-py27_0 ctjacobs

Proceed ([y]/n)? y

http-parser-0. 100% |################################| Time: 0:00:00   1.22 MB/s
httplib2-0.8-p 100% |################################| Time: 0:00:00   2.73 MB/s
smmap-0.9.0-py 100% |################################| Time: 0:00:00   3.22 MB/s
socketpool-0.5 100% |################################| Time: 0:00:00   4.75 MB/s
gitdb-0.6.4-py 100% |################################| Time: 0:00:00   2.53 MB/s
restkit-4.2.2- 100% |################################| Time: 0:00:00 284.64 kB/s
sword2-0.1.15. 100% |################################| Time: 0:00:00 235.09 kB/s
gitpython-2.0. 100% |################################| Time: 0:00:00 858.38 kB/s
pyrdm-0.3-py27 100% |################################| Time: 0:00:00 269.35 kB/s
git-rdm-1.0.1- 100% |################################| Time: 0:00:00   5.77 MB/s
`
Then once I added files, they did not show when typing `git rdm ls`, but were successfully staged. See 
[git-rdm-ls-log.txt](https://github.com/ctjacobs/git-rdm/files/915204/git-rdm-ls-log.txt)

**Comment by ctjacobs** [comment]
When you opted to publish as a private repository, the line `_LOG.info("Publishing as a private repository...")` doesn't appear in the output reported in issue #4. This makes me think that the relevant file paths are being retrieved but the output from `git rdm ls` (which uses `_LOG.info` calls) is just not being shown. I'm not sure why this is happening and I can't reproduce the issue here (I'm not using Anaconda), but I imagine changing from `_LOG.info` to `print` would be a work-around.
